// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpuQnILkaoUg2bIEzZ9rPIieSL1YPA6BE',
    appId: '1:11770579967:web:b0c87d653656dbdf8c35ca',
    messagingSenderId: '11770579967',
    projectId: 'chandigarhuniversity-cedbc',
    authDomain: 'chandigarhuniversity-cedbc.firebaseapp.com',
    storageBucket: 'chandigarhuniversity-cedbc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuCt9pJPpi0yGtQGXYPWeDJDJC03hm7bg',
    appId: '1:11770579967:android:4d02b27d9122dd5d8c35ca',
    messagingSenderId: '11770579967',
    projectId: 'chandigarhuniversity-cedbc',
    storageBucket: 'chandigarhuniversity-cedbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK3ZhhgOq4HpAoXcR-ncDNoigQZNgG1_8',
    appId: '1:11770579967:ios:d0e4073658ae350f8c35ca',
    messagingSenderId: '11770579967',
    projectId: 'chandigarhuniversity-cedbc',
    storageBucket: 'chandigarhuniversity-cedbc.appspot.com',
    iosClientId: '11770579967-4k6ksgfe26d8s8gu6f6t48aoeb0071qp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chandigarhUniversity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK3ZhhgOq4HpAoXcR-ncDNoigQZNgG1_8',
    appId: '1:11770579967:ios:d0e4073658ae350f8c35ca',
    messagingSenderId: '11770579967',
    projectId: 'chandigarhuniversity-cedbc',
    storageBucket: 'chandigarhuniversity-cedbc.appspot.com',
    iosClientId: '11770579967-4k6ksgfe26d8s8gu6f6t48aoeb0071qp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chandigarhUniversity',
  );
}
